name: build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      build-args:
        type: string
        required: false
        default: ''
      cache-scope:
        type: string
        required: false
        default: 'buildkit'
      push:
        type: boolean
        required: false
        default: true
      version:
        type: string
        required: true
      major_only_tag:
        type: boolean
        default: false
        required: false
      revision:
        type: string
        required: false
        default: '1'
      debian_codename:
        type: string
        required: false
        default: bookworm
      latest:
        type: boolean
        required: false
        default: false
      buildkit_version:
        type: string
        required: false
        default: 0.23.2

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}-${{ inputs.name }}-${{ inputs.cache-scope }}
  cancel-in-progress: true

jobs:
  build_package_amd64:
      name: Build AMD64 Image - ${{ inputs.name }}
      runs-on: ubuntu-24.04

      steps:
          - uses: actions/checkout@master
            with:
                fetch-depth: 1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                driver-opts: |
                    image=moby/buildkit:v${{ inputs.buildkit_version }}

          - name: Build and Push container images
            uses: docker/build-push-action@v6
            with:
                platforms: linux/amd64
                build-args: |-
                    ${{ inputs.build-args }}
                    BUILD_VERSION=${{ inputs.version }}
                push: false
                cache-from: type=gha,scope=${{ inputs.cache-scope }}
                cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}

  build_package_arm64:
      name: Build ARM64 Image - ${{ inputs.name }}
      runs-on: ubuntu-24.04-arm

      steps:
          - uses: actions/checkout@master
            with:
                fetch-depth: 1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
                driver-opts: |
                    image=moby/buildkit:v${{ inputs.buildkit_version }}

          - name: Build and Push container images
            uses: docker/build-push-action@v6
            with:
                platforms: linux/arm64
                build-args: |-
                    ${{ inputs.build-args }}
                    BUILD_VERSION=${{ inputs.version }}
                push: false
                cache-from: type=gha,scope=${{ inputs.cache-scope }}-arm
                cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}-arm

  build_package:
    name: Build package - ${{ inputs.name }}
    runs-on: ubuntu-24.04
    needs:
        - build_package_amd64
        - build_package_arm64

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - uses: bitcompat/compute-ghcr-revision-action@v1
        id: version-tags
        with:
          version: '${{ inputs.version }}'
          debian_codename: '${{ inputs.debian_codename }}'
          major_only_tag: ${{ inputs.major_only_tag && 'true' || 'false' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.23.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ inputs.push == true }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        name: Extract docker image metadata
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
            public.ecr.aws/bitcompat/${{ github.event.repository.name }},enable=${{ github.repository_owner == 'bitcompat' }}
          tags: |
            ${{ inputs.latest && 'latest' || '' }}
            ${{ steps.version-tags.outputs.tags }}
            type=sha
            type=sha,format=long

      - name: Build and Push container images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          build-args: |-
            ${{ inputs.build-args }}
            BUILD_VERSION=${{ inputs.version }}
          push: ${{ inputs.push }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |-
            type=gha,scope=${{ inputs.cache-scope }}
            type=gha,scope=${{ inputs.cache-scope }}-arm
          cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}

      - name: Setup CRANE
        uses: imjasonh/setup-crane@v0.4

      - name: Flatten images
        id: flatten_images
        run: |
          set -ex
          DIGEST=""
          while read -r IMG; do
            export OUT=$(crane flatten "$IMG")
            DIGEST+="$IMG@$(echo "$OUT" | awk 'END{print}' | cut -d'@' -f2) "
          done <<< $(echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '.tags[]')
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
